export type ProductGender = "Men" | "Women" | "Kids";

export interface ProductSpec {
  material?: string;
  fit?: string;
  washCare?: string[];
}

export interface ProductRatings {
  average: number;
  count: number;
}

export interface ProductImage {
  id?: string | number;
  image_type?: string;
  imageType?: string;
  image_url?: string;
  imageUrl?: string;
  url?: string;
  secure_url?: string;
  public_id?: string;
  product_id?: string | number;
  productId?: string | number;
  variant_id?: string | number;
  variantId?: string | number;
  barcode?: string;
  ean_code?: string;
  eanCode?: string;
  colour?: string;
  color?: string;
}

export interface ProductVariant {
  id: string | number;
  variantId?: string | number;
  variant_id?: string | number;
  productId?: string | number;
  product_id?: string | number;
  designCode?: string;
  design_code?: string;
  patternType?: string;
  pattern_type?: string;
  patternCode?: string;
  pattern_code?: string;
  groupKey?: string;
  group_key?: string;
  routeKey?: string;
  route_key?: string;
  size?: string;
  colour?: string;
  color?: string;
  barcode?: string;
  ean_code?: string;
  eanCode?: string;
  mrp?: number;
  original_price_b2c?: number;
  final_price_b2c?: number;
  original_price_b2b?: number;
  final_price_b2b?: number;
  cost_price?: number;
  sale_price?: number;
  price?: number;
  b2c_discount_pct?: number;
  b2b_discount_pct?: number;
  discount_b2c?: number;
  discount_b2b?: number;
  on_hand?: number;
  onHand?: number;
  reserved?: number;
  available_qty?: number;
  availableQty?: number;
  in_stock?: boolean;
  inStock?: boolean;
  image_url?: string;
  imageUrl?: string;
  front_image_url?: string;
  frontImageUrl?: string;
  back_image_url?: string;
  backImageUrl?: string;
  main_image_url?: string;
  mainImageUrl?: string;
  images?: Array<string | ProductImage>;
  weight?: number;
  weight_kg?: number;
  length?: number;
  width?: number;
  height?: number;
  hsnCode?: string;
  hsn_code?: string;
  hsnPercentage?: number;
  hsn_percentage?: number;
  material?: string;
  fitType?: string;
  fit_type?: string;
  markCode?: string;
  mark_code?: string;
  raw?: any;
  [key: string]: any;
}

export interface Product {
  id: string | number;
  productId?: string | number;
  product_id?: string | number;
  variantId?: string | number;
  variant_id?: string | number;
  primaryVariantId?: string | number;
  primary_variant_id?: string | number;
  designCode?: string;
  design_code?: string;
  patternType?: string;
  pattern_type?: string;
  patternCode?: string;
  pattern_code?: string;
  groupKey?: string;
  group_key?: string;
  designKey?: string;
  design_key?: string;
  routeKey?: string;
  route_key?: string;
  title: string;
  name?: string;
  product_name?: string;
  description: string;
  brand?: string;
  brand_name?: string;
  gender: ProductGender;
  category?: ProductGender;
  categoryId: string;
  category_id?: string;
  categoryName?: string;
  category_name?: string;
  categorySlug?: string;
  category_slug?: string;
  parentCategoryId?: string;
  parent_category_id?: string;
  parentCategoryName?: string;
  parent_category_name?: string;
  parentCategorySlug?: string;
  parent_category_slug?: string;
  categoryPath?: string;
  category_path?: string;
  price: number;
  originalPrice?: number;
  original_price?: number;
  original_price_b2c?: number;
  final_price_b2c?: number;
  originalPriceB2b?: number;
  original_price_b2b?: number;
  finalPriceB2b?: number;
  final_price_b2b?: number;
  cost_price?: number;
  salePrice?: number;
  sale_price?: number;
  selling_price?: number;
  discounted_price?: number;
  mahaveer_price?: number;
  discount?: number;
  discount_b2c?: number;
  discount_b2b?: number;
  discount_percentage?: number;
  discount_percent?: number;
  b2c_discount_pct?: number;
  b2b_discount_pct?: number;
  isSale?: boolean;
  images: any[];
  frontImageUrl?: string;
  front_image_url?: string;
  backImageUrl?: string;
  back_image_url?: string;
  mainImageUrl?: string;
  main_image_url?: string;
  imageUrl?: string;
  image_url?: string;
  barcode?: string;
  ean_code?: string;
  eanCode?: string;
  barcodes?: string[];
  ean_codes?: string[];
  eanCodes?: string[];
  size?: string;
  colour?: string;
  color?: string;
  selectedColor?: string;
  selected_color?: string;
  selectedColour?: string;
  selected_colour?: string;
  sizes: string[];
  allSizes?: string[];
  all_sizes?: string[];
  colors: string[];
  colours?: string[];
  stockBySize: Record<string, number>;
  specs: ProductSpec;
  ratings: ProductRatings;
  createdAt: string;
  created_at?: string;
  onHand?: number;
  on_hand?: number;
  reserved?: number;
  reserved_qty?: number;
  reservedQty?: number;
  available_qty?: number;
  availableQty?: number;
  in_stock?: boolean;
  inStock?: boolean;
  mrp?: number;
  fitType?: string;
  fit_type?: string;
  markCode?: string;
  mark_code?: string;
  weight?: number;
  weight_kg?: number;
  length?: number;
  width?: number;
  height?: number;
  hsnCode?: string;
  hsn_code?: string;
  hsnPercentage?: number;
  hsn_percentage?: number;
  variants?: ProductVariant[];
  colorVariants?: ProductVariant[];
  color_variants?: ProductVariant[];
  variantCount?: number;
  variant_count?: number;
  colorVariantCount?: number;
  color_variant_count?: number;
  raw?: any;
  [key: string]: any;
}
